import Vue from 'vue'
import Vuex from 'vuex'

Vue.use(Vuex)

export default new Vuex.Store({
  state: {
    foods: [
      { name: 'Ail', quality: 'T', vitamin_C: 0, type: 'L', note: '' },
      { name: 'Asperge', quality: 'D', vitamin_C: 5.6, type: 'L', note: '' },
      { name: 'Aubergine', quality: 'C', vitamin_C: 2.2, type: 'L', note: '' },
      { name: 'Batavia', quality: 'M', vitamin_C: 0, type: 'L', note: 'Laxatif. Peut être donné tous les jours en quantité modérée ( 2 à 3 feuilles ). En quantité très modérée les toutes premières fois pour les cobayes non habitués.' },
      { name: 'Bette', quality: 'D', vitamin_C: 30, type: 'L', note: 'Très riche en acide oxalique ( 600 mg pour 1 g) Risquent de favoriser les problèmes d\'urolithiases s\'ils sont consommés en excès, même pour des cochons d\'Inde en bonne santé. Déconseillé pour les cobayes ayant des problèmes urinaires.' },
      { name: 'Betterave rouge', quality: 'D', vitamin_C: 30, type: 'L', note: 'Riche en sucre, peu de valeur nutritive, favorise l\'obésité. A proscrire chez les cobayes ayant des problèmes urinaires.' },
      { name: 'Bourrache', quality: 'C', vitamin_C: 35, type: 'L', note: '' },
      { name: 'Brocoli', quality: 'C', vitamin_C: 89.2, type: 'L', note: 'Peut provoquer des ballonnements en trop grande quantité.' },
      { name: 'Carotte', quality: 'D', vitamin_C: 5.9, type: 'L', note: 'Contient de l\'acide oxalique déconseillé en cas d\'obésité (sucres).' },
      { name: 'Céleri rave', quality: 'C', vitamin_C: 8, type: 'L', note: 'Diurétique. Peut provoquer des selles molles chez certains cobayes sensibles.' },
      { name: 'Champignons de Paris', quality: 'D', vitamin_C: 0, type: 'L', note: '' },
      { name: 'Chicorée', quality: 'C', vitamin_C: 24, type: 'L', note: '' },
      { name: 'Chou chinois', quality: 'C', vitamin_C: 3.2, type: 'L', note: '' },
      { name: 'Chou de Bruxelles', quality: 'M', vitamin_C: 85, type: 'L', note: 'Peut provoquer des ballonnements en trop grande quantité.' },
      { name: 'Chou fleur (sans feuille)', quality: 'M', vitamin_C: 48.2, type: 'L', note: 'Peut provoquer des ballonnements en trop grande quantité.' },
      { name: 'Chou frisé', quality: 'M', vitamin_C: 120, type: 'L', note: 'Peut provoquer des ballonnements en trop grande quantité.' },
      { name: 'Chou vert', quality: 'M', vitamin_C: 36.6, type: 'L', note: 'Peut provoquer des ballonnements en trop grande quantité.' },
      { name: 'Ciboulette', quality: 'T', vitamin_C: 0, type: 'L', note: '' },
      { name: 'Concombre', quality: 'C', vitamin_C: 2.8, type: 'L', note: 'Riche en eau. Conseillé pour les cobayes buvant peu ou ayant des problèmes urinaires.' },
      { name: 'Courge', quality: 'M', vitamin_C: 9.6, type: 'L', note: 'Légèrement sucré.' },
      { name: 'Courgette', quality: 'C', vitamin_C: 1.9, type: 'L', note: '' },
      { name: 'Cresson', quality: 'M', vitamin_C: 43, type: 'L', note: '' },
      { name: 'Endive (chicorée, chicon)', quality: 'C', vitamin_C: 6.5, type: 'L', note: '2 ou 3 feuilles, riche en eau.' },
      { name: 'Épinard', quality: 'D', vitamin_C: 28.1, type: 'L', note: 'Peut provoquer des selles molles chez certains cobayes sensibles. Très riche en acide oxalique. Risque de favoriser les problèmes d\'urolithiases s\'ils sont consommés en excès, même pour des cochons d\'Inde en bonne santé. Déconseillé chez les cobayes ayant des problèmes urinaires.' },
      { name: 'Fanes de betteraves', quality: 'P', vitamin_C: 0, type: 'L', note: 'Très riche en acide oxalique.' },
      { name: 'Fanes de carotte', quality: 'C', vitamin_C: 0, type: 'L', note: 'Peut être donné quotidiennement.' },
      { name: 'Fanes de fenouil', quality: 'C', vitamin_C: 0, type: 'L', note: 'Peut être donné quotidiennement.' },
      { name: 'Fanes de navet', quality: 'P', vitamin_C: 0, type: 'L', note: 'Très riche en calcium.' },
      { name: 'Fanes de radis', quality: 'C', vitamin_C: 0, type: 'L', note: 'Peut provoquer des selles molles chez certains cobayes sensibles.' },
      { name: 'Fenouil', quality: 'C', vitamin_C: 12, type: 'L', note: 'Peut être donné quotidiennement, riche en fibres.' },
      { name: 'Frisée', quality: 'M', vitamin_C: 0, type: 'L', note: 'Laxatif. Peut être donné tous les jours en quantité modérée ( 2 à 3 feuilles ). En quantité très modérée les toutes premières fois pour les cobayes non habitués.' },
      { name: 'Feuille de chene', quality: 'M', vitamin_C: 0, type: 'L', note: 'Laxatif. Peut être donné tous les jours en quantité modérée ( 2 à 3 feuilles ). En quantité très modérée les toutes premières fois pour les cobayes non habitués.' },
      { name: 'Haricots verts frais', quality: 'M', vitamin_C: 16.3, type: 'L', note: 'Choisir extra frais. Ne pas en donner trop à la fois. Riche en acide oxalique : déconseillé pour les cobayes ayant des problèmes urinaires.' },
      { name: 'Haricots coco plats', quality: 'M', vitamin_C: 0, type: 'L', note: '' },
      { name: 'Laitue', quality: 'P', vitamin_C: 0, type: 'L', note: 'Trop de nitrate !' },
      { name: 'Mache', quality: 'M', vitamin_C: 38.2, type: 'L', note: 'Peut provoquer des crottes molles chez certains cobayes sensibles.' },
      { name: 'Mesclun', quality: 'D', vitamin_C: 0, type: 'L', note: '' },
      { name: 'Navet', quality: 'M', vitamin_C: 21, type: 'L', note: 'En quantité modérée car peut provoquer des ballonnements.' },
      { name: 'Oignon', quality: 'T', vitamin_C: 0, type: 'L', note: '' },
      { name: 'Panais', quality: 'C', vitamin_C: 17, type: 'L', note: '' },
      { name: 'Petit pois frais avec cosses', quality: 'M', vitamin_C: 14.2, type: 'L', note: '' },
      { name: 'Pissenlit', quality: 'C', vitamin_C: 37.5, type: 'L', note: 'Feuilles et fleurs sont consommables' },
      { name: 'Poireau', quality: 'T', vitamin_C: 0, type: 'L', note: '' },
      { name: 'Poivron', quality: 'C', vitamin_C: 80.4, type: 'L', note: 'Peut être donné quotidiennement. Le poivron rouge contient beaucoup plus de Vitamine A C que le jaune ou le vert.' },
      { name: 'Potiron', quality: 'M', vitamin_C: 0.84, type: 'L', note: 'Légèrement sucré.' },
      { name: 'Pourpier', quality: 'C', vitamin_C: 21, type: 'L', note: '' },
      { name: 'Radis', quality: 'C', vitamin_C: 14.8, type: 'L', note: 'On peut donner aussi les fanes. Peut créer des ballonnements si donnés en trop grande quantité.' },
      { name: 'Radis noir', quality: 'C', vitamin_C: 6.4, type: 'L', note: '' },
      { name: 'Raifort', quality: 'C', vitamin_C: 97.3, type: 'L', note: '' },
      { name: 'Rhubarbe', quality: 'P', vitamin_C: 0, type: 'L', note: 'Forte acidité.' },
      { name: 'Romaine', quality: 'M', vitamin_C: 5, type: 'L', note: 'Laxatif. Peut être donné tous les jours en quantité modérée ( 2 à 3 feuilles ). En quantité très modérée les toutes premières fois pour les cobayes non habitués.' },
      { name: 'Roquette', quality: 'C', vitamin_C: 0, type: 'L', note: '' },
      { name: 'Rutabaga', quality: 'C', vitamin_C: 25, type: 'L', note: 'En petite quantité.' },
      { name: 'Salsifis', quality: 'C', vitamin_C: 8, type: 'L', note: '' },
      { name: 'Scarole', quality: 'M', vitamin_C: 0, type: 'L', note: 'Laxatif. Peut être donné tous les jours en quantité modérée ( 2 à 3 feuilles ). En quantité très modérée les toutes premières fois pour les cobayes non habitués.' },
      { name: 'Tomate', quality: 'C', vitamin_C: 13.7, type: 'L', note: 'Riche en eau, mais peut provoquer des diarrhées.' },
      { name: 'Tomate cerise', quality: 'C', vitamin_C: 18.4, type: 'L', note: 'Riche en eau, mais peut provoquer des diarrhées.' },
      { name: 'Topinambour', quality: 'C', vitamin_C: 4, type: 'L', note: 'Riche en eau et pauvre en calcium et phosphore.' },
      { name: 'Trèfle', quality: 'M', vitamin_C: 0, type: 'V', note: 'Peut provoquer des ballonnement en trop grande quantité.' },
      { name: 'Feuilles de fraisier', quality: 'C', vitamin_C: 0, type: 'V', note: '' },
      { name: 'Feuilles de framboisier', quality: 'C', vitamin_C: 0, type: 'V', note: 'Attention à retirer les épines qui peuvent blesser les parois de la cavité buccale.' },
      { name: 'Feuilles de mûrier', quality: 'C', vitamin_C: 0, type: 'V', note: 'Attention à retirer les épines qui peuvent blesser les parois de la cavité buccale.' },
      { name: 'Feuilles de noisetier', quality: 'C', vitamin_C: 0, type: 'V', note: '2 ou 3 feuilles par ration.' },
      { name: 'Feuilles de saule', quality: 'C', vitamin_C: 0, type: 'V', note: '' },
      { name: 'Herbe fraîche', quality: 'TC', vitamin_C: 0, type: 'V', note: '' },
      { name: 'Luzerne fraîche', quality: 'D', vitamin_C: 0, type: 'V', note: 'Trop riche en calcium.' },
      { name: 'Ortie', quality: 'C', vitamin_C: 0, type: 'V', note: 'L\'ortie est riche en fer, en calcium, en potassium, en magnésium ainsi qu\'en vitamine A et C. A faire sécher pour lui ôter ses propriétés urticantes. Diurétique, Antidiarrhéique.' },
      { name: 'Pissenlits', quality: 'C', vitamin_C: 37, type: 'V', note: 'Feuilles et fleurs sont mangeables.' },
      { name: 'Aneth', quality: 'M', vitamin_C: 21, type: 'HA', note: '' },
      { name: 'Angélique', quality: 'C', vitamin_C: 0, type: 'HA', note: '' },
      { name: 'Basilic', quality: 'M', vitamin_C: 18, type: 'HA', note: '' },
      { name: 'Cerfeuil', quality: 'D', vitamin_C: 50, type: 'HA', note: '' },
      { name: 'Coriandre', quality: 'C', vitamin_C: 27, type: 'HA', note: '' },
      { name: 'Estragon', quality: 'M', vitamin_C: 50, type: 'HA', note: 'Riche en acide oxalique.' },
      { name: 'Fenouil aromatique', quality: 'C', vitamin_C: 0, type: 'HA', note: '' },
      { name: 'Menthe', quality: 'C', vitamin_C: 31.8, type: 'HA', note: '' },
      { name: 'Oseille', quality: 'P', vitamin_C: 48, type: 'HA', note: 'Riche en acide oxalique.' },
      { name: 'Persil (plat, frisé)', quality: 'C', vitamin_C: 133, type: 'HA', note: 'Ne pas donner à une femelle qui allaite : Coupe les montées de lait. Très riche en vitamine C' },
      { name: 'Sarriette', quality: 'P', vitamin_C: 0, type: 'HA', note: '' },
      { name: 'Sauge', quality: 'P', vitamin_C: 0, type: 'HA', note: '' },
      { name: 'Thym', quality: 'M', vitamin_C: 0, type: 'HA', note: '' },
      { name: 'Abricot', quality: 'C', vitamin_C: 10, type: 'F', note: '' },
      { name: 'Ananas', quality: 'C', vitamin_C: 47.8, type: 'F', note: '' },
      { name: 'Banane', quality: 'C', vitamin_C: 8.7, type: 'F', note: 'Un tronçon de 2 cm. Eviter en cas d\'obésité.' },
      { name: 'Canneberge', quality: 'C', vitamin_C: 13.3, type: 'F', note: '' },
      { name: 'Cerise', quality: 'M', vitamin_C: 10, type: 'F', note: 'Trés sucré.' },
      { name: 'Clémentine', quality: 'C', vitamin_C: 48.8, type: 'F', note: '' },
      { name: 'Coing', quality: 'C', vitamin_C: 15, type: 'F', note: '' },
      { name: 'Datte', quality: 'D', vitamin_C: 1.5, type: 'F', note: 'Riche en acide oxalique.' },
      { name: 'Figues', quality: 'P', vitamin_C: 2, type: 'F', note: 'Riche en acide oxalique.' },
      { name: 'Fraise', quality: 'C', vitamin_C: 67, type: 'F', note: '' },
      { name: 'Framboise', quality: 'C', vitamin_C: 26.2, type: 'F', note: '' },
      { name: 'Fruit de la passion', quality: 'C', vitamin_C: 30, type: 'F', note: 'A éviter chez les cobayes souffrant d\'obésité.' },
      { name: 'Goyave', quality: 'M', vitamin_C: 228.3, type: 'F', note: 'A éviter chez les cobayes souffrant d\'obésité car très riche en sucre.' },
      { name: 'Groseille', quality: 'M', vitamin_C: 41, type: 'F', note: 'Sucré.' },
      { name: 'kaki', quality: 'M', vitamin_C: 66, type: 'F', note: 'Sucré.' },
      { name: 'Kiwi', quality: 'C', vitamin_C: 92.7, type: 'F', note: 'Diurétique. Peut provoquer des selles molles chez certains cobayes sensibles.' },
      { name: 'Litchi', quality: 'M', vitamin_C: 71.5, type: 'F', note: 'A éviter chez les cobayes souffrant d\'obésité car très riche en sucre.' },
      { name: 'Mandarine', quality: 'M', vitamin_C: 26.7, type: 'F', note: 'Sucré.' },
      { name: 'Mangue', quality: 'M', vitamin_C: 36.4, type: 'F', note: 'Sucré.' },
      { name: 'Melon', quality: 'M', vitamin_C: 36.7, type: 'F', note: 'A éviter chez les cobayes souffrant de problèmes urinaires.' },
      { name: 'Melon vert/jaune', quality: 'C', vitamin_C: 36.7, type: 'F', note: 'Sucré.' },
      { name: 'Myrtilles', quality: 'M', vitamin_C: 20, type: 'F', note: 'Sucré et acide.' },
      { name: 'Nectarine', quality: 'M', vitamin_C: 5.4, type: 'F', note: 'Sucré.' },
      { name: 'Noix de coco', quality: 'M', vitamin_C: 3.3, type: 'F', note: 'Riche en vitamine D.' },
      { name: 'Orange', quality: 'M', vitamin_C: 53.2, type: 'F', note: '' },
      { name: 'Pamplemousse', quality: 'M', vitamin_C: 42, type: 'F', note: '' },
      { name: 'Pastèque', quality: 'D', vitamin_C: 8.1, type: 'F', note: 'Déconseillé pour tous les cobayes mêmes en bonne santé. Très déconseillé chez les cobayes souffrant de problèmes urinaires car trop riche en calcium.' },
      { name: 'Poire', quality: 'M', vitamin_C: 4.3, type: 'F', note: 'Peut provoquer des ballonnements chez certains cobayes.' },
      { name: 'Pomelo', quality: 'M', vitamin_C: 40.9, type: 'F', note: 'Sucré et acide.' },
      { name: 'Pomme', quality: 'M', vitamin_C: 4.6, type: 'F', note: 'Modérément pour éviter l\'obésité. Certains cobayes sont allergiques à la pectine contenue dans la peau. À éplucher.' },
      { name: 'Pruneau', quality: 'D', vitamin_C: 0.6, type: 'F', note: 'Risque de diarrhée.' },
      { name: 'Raisin', quality: 'M', vitamin_C: 4, type: 'F', note: 'A modérer car très riche en sucre et peut favoriser l\'obésité.' }
    ]
  },
  getters: {
    foods: state => {
      return state.foods
    }
  },
  mutations: { },
  actions: { }
})
